/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import controle.ConexaoBD;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansUsuario;
import modeloBeans.ModeloTabela;
import modeloDao.DaoUsuario;

/**
 *
 * @author User
 */
public class CadastroUsuario2 extends javax.swing.JInternalFrame {

   BeansUsuario mod = new BeansUsuario();
   DaoUsuario dao = new DaoUsuario();
   ConexaoBD conex = new ConexaoBD();
   
   int flag=0;
   
   
    public CadastroUsuario2() {
        initComponents();
        preencherTabela("select *from usuarios");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbAdicionar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jtConfirma = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jbPesquisar = new javax.swing.JButton();
        jtPesquisar = new javax.swing.JTextField();
        jtCod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtUsuario = new javax.swing.JTable();

        setClosable(true);

        jbSalvar.setText("Salvar");
        jbSalvar.setEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbFechar.setText("Fechar");
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbAdicionar.setText("Novo");
        jbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Principais"));

        jLabel3.setText("Senha");

        jtLogin.setEnabled(false);
        jtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtLoginActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuário");

        jtNome.setEnabled(false);

        jtSenha.setEnabled(false);

        jLabel5.setText("Confirma");

        jtConfirma.setEnabled(false);

        jLabel8.setText("Nome");

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jtCod.setEnabled(false);

        jLabel1.setText("Codigo");

        jtUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtUsuario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtLogin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(201, 201, 201))
                        .addComponent(jtNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(133, 133, 133))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAdicionar)
                .addGap(4, 4, 4)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(jbFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAdicionar)
                    .addComponent(jbAlterar)
                    .addComponent(jbExcluir)
                    .addComponent(jbCancelar)
                    .addComponent(jbSalvar)
                    .addComponent(jbFechar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        
        jtNome.setText("");
        jtLogin.setText("");
        jtSenha.setText("");
        jtConfirma.setText("");

        jbCancelar.setEnabled(false);
        jbSalvar.setEnabled(false);
       
        jtNome.setEnabled(false);
        jtLogin.setEnabled(false);
        jtSenha.setEnabled(false);
        jtConfirma.setEnabled(false);
        
       
        jbAdicionar.setEnabled(true);
        jbExcluir.setEnabled(true);
        jbAlterar.setEnabled(true);

    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        flag=2;
        jtNome.setEnabled(true);
        jtLogin.setEnabled(true);
        jtSenha.setEnabled(true);
        jtConfirma.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbSalvar.setEnabled(true);
        jbAdicionar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbAlterar.setEnabled(false);
        
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarActionPerformed
        flag = 1;
        jbCancelar.setEnabled(true);
        jbSalvar.setEnabled(true);
        jtNome.setEnabled(true);
        jtLogin.setEnabled(true);
        jtSenha.setEnabled(true);
        jtConfirma.setEnabled(true);
        jbAdicionar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbAlterar.setEnabled(false);
    }//GEN-LAST:event_jbAdicionarActionPerformed

    private void jtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtLoginActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
    if (jtNome.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "preencha o Nome para continuar");
        jtNome.requestFocus(); 
    } else if(jtLogin.getText().isEmpty()){
         JOptionPane.showMessageDialog(null, "preencha o Usuário para continuar");
         jtLogin.requestFocus();
     } else if (jtConfirma.getText().isEmpty()) {
         JOptionPane.showMessageDialog(null, "preencha o Confirmar Senha para continuar");
     jtConfirma.requestFocus();
     } else if  (jtSenha.getText().isEmpty()) {
         JOptionPane.showMessageDialog(null, "preencha a Senha para continuar");
         jtSenha.requestFocus();       
     } else 
       if(flag==1) {
           
           mod.setUsuNome(jtNome.getText());
           mod.setUsuUsu(jtLogin.getText());
           mod.setUsuSenha(jtSenha.getText());
           dao.Salvar(mod);
           jtNome.setText("");
           jtLogin.setText("");
           jtSenha.setText("");
           jtConfirma.setText("");
           jtPesquisar.setText("");
        jtCod.setEnabled(false);
        jtNome.setEnabled(false);
        jtLogin.setEnabled(false);
        jtSenha.setEnabled(false);
        jtConfirma.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbSalvar.setEnabled(false);
        jbAdicionar.setEnabled(true);
        jbExcluir.setEnabled(true);
        jbAlterar.setEnabled(true);
           jtCod.setText("");
           jtNome.setText("");
           jtLogin.setText("");
           jtSenha.setText("");
           jtConfirma.setText("");
           jtPesquisar.setText("");
         
       }else{
          mod.setUsuCod(Integer.parseInt(jtCod.getText()));
            mod.setUsuNome(jtNome.getText());
           mod.setUsuUsu(jtLogin.getText());
           mod.setUsuSenha(jtSenha.getText());
           dao.Alterar(mod);
            jtNome.setEnabled(false);
        jtLogin.setEnabled(false);
        jtSenha.setEnabled(false);
        jtConfirma.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbSalvar.setEnabled(false);
        jbAdicionar.setEnabled(true);
        jbExcluir.setEnabled(true);
        jbAlterar.setEnabled(true);
           jtCod.setText("");
           jtNome.setText("");
           jtLogin.setText("");
           jtSenha.setText("");
           jtConfirma.setText("");
           jtPesquisar.setText("");
     }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
this.dispose();    
    }//GEN-LAST:event_jbFecharActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
       mod.setUsuPesquisa(jtPesquisar.getText());
        BeansUsuario model = dao.buscaUsuario(mod);
        
        jtCod.setText(String.valueOf(model.getUsuCod()));
        jtLogin.setText(model.getUsuUsu());
        jtNome.setText(model.getUsuNome());
        jtSenha.setText(model.getUsuSenha());
        jtConfirma.setText(model.getUsuSenha());
        
        jbExcluir.setEnabled(true);
        jbAlterar.setEnabled(true);
                                                     
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja realmente excluir?");
        if(resposta == JOptionPane.YES_OPTION){
            mod.setUsuCod(Integer.parseInt(jtCod.getText()));
            dao.Excluir(mod);
        }
           jtCod.setText("");
           jtNome.setText("");
           jtLogin.setText("");
           jtSenha.setText("");
           jtConfirma.setText("");
           jtPesquisar.setText("");
    
         
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUsuarioMouseClicked
       String usu_nome = ""+jtUsuario.getValueAt (jtUsuario.getSelectedRow(), 1);
       conex.conexao();
       conex.executaSql ("select * from usuarios where usu_nome='"+usu_nome+"'");
       try{
           conex.rs.first();
           jtCod.setText(String.valueOf(conex.rs.getInt("usu_cod")));
           jtNome.setText(conex.rs.getString("usu_nome"));
           jtLogin.setText(conex.rs.getString("usu_usu"));
       }catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,"Erro ao selecionar dados"+ex);
       }
       conex.desconecta();
    
       
    }//GEN-LAST:event_jtUsuarioMouseClicked

    public  void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"ID","Nome Usuario"};
        conex.conexao();
        conex.executaSql(Sql);
        try {
            conex.rs.first(); 
            do{
 dados.add(new Object[]{conex.rs.getInt("usu_cod"),conex.rs.getString("usu_nome")});
            }while(conex.rs.next()); 
            
        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane,"Erro ao preencher ArrayList"+ex);
                }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
       
        jtUsuario.setModel(modelo);
        jtUsuario.getColumnModel().getColumn(0).setPreferredWidth(23);
        jtUsuario.getColumnModel().getColumn(0).setResizable(false);
        jtUsuario.getColumnModel().getColumn(1).setPreferredWidth(180);
        jtUsuario.getColumnModel().getColumn(1).setResizable(false);
     
        jtUsuario.getTableHeader().setReorderingAllowed(false);
        jtUsuario.setAutoResizeMode(jtUsuario.AUTO_RESIZE_OFF);
        jtUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
        
        
    }
    
        
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JTextField jtCod;
    private javax.swing.JPasswordField jtConfirma;
    private javax.swing.JTextField jtLogin;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtPesquisar;
    private javax.swing.JPasswordField jtSenha;
    private javax.swing.JTable jtUsuario;
    // End of variables declaration//GEN-END:variables
}
